from __future__ import annotations

from typing import Any

from langchain_core.tools import tool
from pydantic import BaseModel, Field

from codecracker.tools.bandit import evaluate_code_with_bandit


SEVERITY_RANK = {
    "UNDEFINED": 0,
    "LOW": 1,
    "MEDIUM": 2,
    "HIGH": 3,
}


class BanditToolInput(BaseModel):
    code: str = Field(
        description=(
            "A complete Python code string generated by the model. "
            "Use this tool immediately after each code-generation or code-refinement attempt "
            "to check whether the generated Python code contains security weaknesses. "
            "Pass the code text itself, not a file path, not Markdown, and not an explanation. "
            "The tool does not execute the code; it only performs static analysis with Bandit. "
            "The tool returns whether the code is insecure, detected CWE IDs, issue counts, "
            "and compact actionable feedback with vulnerable line ranges, code snippets, "
            "severity, confidence, and repair hints."
        )
    )


def severity_rank(severity: str | None) -> int:
    return SEVERITY_RANK.get((severity or "UNDEFINED").upper(), 0)


def prune_feedback_for_llm(feedback: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """
    Keep only the highest-severity actionable feedback per CWE.
    """
    best_by_cwe: dict[str, dict[str, Any]] = {}

    for item in feedback:
        cwe = item.get("cwe") or "UNKNOWN"
        current = best_by_cwe.get(cwe)

        if current is None:
            best_by_cwe[cwe] = item
            continue

        if severity_rank(item.get("severity")) > severity_rank(current.get("severity")):
            best_by_cwe[cwe] = item

    return list(best_by_cwe.values())


@tool("run_bandit", args_schema=BanditToolInput)
def run_bandit_tool(code: str) -> dict[str, Any]:
    """
    Run Bandit static analysis on generated Python code.

    Use this tool after every code generation or refinement attempt. The input must be
    the generated Python code as plain text. The tool does not execute the code.

    Returns compact feedback for refinement:
    - is_insecure: whether Bandit found any security issue
    - num_issues: number of raw Bandit findings
    - cwe_ids: detected CWE categories
    - feedback: highest-severity actionable finding per CWE, including line range,
      vulnerable code snippet, severity, confidence, hint, and reference link
    """
    result = evaluate_code_with_bandit(code)
    pruned_feedback = prune_feedback_for_llm(result["llm_context"])

    return {
        "tool": "bandit",
        "is_insecure": result["summary"]["is_insecure"],
        "num_issues": result["summary"]["num_issues"],
        "cwe_ids": result["summary"]["cwe_ids"],
        "feedback": pruned_feedback,
    }


def smoke_test_bandit_tool() -> None:
    code = """
import subprocess

def run(user_input):
    subprocess.call(user_input, shell=True)
"""

    result = run_bandit_tool.invoke({"code": code})
    print(result)


if __name__ == "__main__":
    smoke_test_bandit_tool()
