from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
from typing import Any

from langchain_core.tools import tool
from pydantic import BaseModel, Field

from codecracker.tools.bandit_tool import prune_feedback_for_llm, severity_rank
from codecracker.tools.bandit import evaluate_code_with_bandit
from codecracker.tools.semgrep import evaluate_code_with_semgrep


class SecurityToolInput(BaseModel):
    code: str = Field(
        description=(
            "A complete Python code string generated by the model. "
            "Use this tool after code generation to run security analysis with both "
            "Bandit and Semgrep in one step. Pass the code text itself, not a file path, "
            "not Markdown, and not an explanation. The tool does not execute the code."
        )
    )


SEMGREP_SEVERITY_RANK = {
    "INFO": 0,
    "WARNING": 1,
    "LOW": 1,
    "ERROR": 3,
    "HIGH": 3,
}


def _semgrep_severity_rank(severity: str | None) -> int:
    return SEMGREP_SEVERITY_RANK.get((severity or "INFO").upper(), 0)


def _build_semgrep_llm_context(summary: dict[str, Any]) -> list[dict[str, Any]]:
    return [
        {
            "cwe": issue["cwe"][0] if issue.get("cwe") else None,
            "fault": {
                "start_line": issue["line_number"],
                "end_line": issue["line_number"],
                "code": issue["snippet"],
            },
            "severity": issue["severity"],
            "confidence": None,
            "hint": issue["message"],
            "reference": None,
            "source": {
                "tool": "semgrep",
                "rule_id": issue["check_id"],
                "rule_name": issue["check_id"],
            },
        }
        for issue in summary["issues"]
    ]


def _combined_severity(item: dict[str, Any]) -> int:
    source_tool = item.get("source", {}).get("tool")
    if source_tool == "bandit":
        return severity_rank(item.get("severity"))
    return _semgrep_severity_rank(item.get("severity"))


def _merge_feedback(
    bandit_feedback: list[dict[str, Any]],
    semgrep_feedback: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    best_by_key: dict[tuple[str, str, int | None], dict[str, Any]] = {}

    for item in [*bandit_feedback, *semgrep_feedback]:
        cwe = item.get("cwe") or "UNKNOWN"
        source_tool = item.get("source", {}).get("tool", "unknown")
        start_line = item.get("fault", {}).get("start_line")
        key = (cwe, source_tool, start_line)
        current = best_by_key.get(key)

        if current is None or _combined_severity(item) > _combined_severity(current):
            best_by_key[key] = item

    merged = list(best_by_key.values())
    merged.sort(
        key=lambda item: (
            -(item.get("fault", {}).get("start_line") is not None),
            -_combined_severity(item),
            item.get("fault", {}).get("start_line") or 0,
        )
    )
    return merged


@tool(
    "run_security_checks",
    args_schema=SecurityToolInput,
    response_format="content_and_artifact",
)
def run_security_checks_tool(code: str) -> dict[str, Any]:
    """
    Run Bandit and Semgrep security analysis on generated Python code in parallel.

    Use this tool after code generation to get combined security feedback from both tools.
    The input must be the generated Python code as plain text. The tool does not execute code.

    Returns:
    - is_insecure: whether either tool found any issue
    - cwe_ids: combined CWE categories
    - feedback: merged actionable findings for refinement
    - tools: per-tool summary for Bandit and Semgrep
    """
    with ThreadPoolExecutor(max_workers=2) as executor:
        bandit_future = executor.submit(evaluate_code_with_bandit, code)
        semgrep_future = executor.submit(evaluate_code_with_semgrep, code)
        bandit_result = bandit_future.result()
        semgrep_result = semgrep_future.result()

    bandit_feedback = prune_feedback_for_llm(bandit_result["llm_context"])
    semgrep_feedback = _build_semgrep_llm_context(semgrep_result["summary"])
    merged_feedback = _merge_feedback(bandit_feedback, semgrep_feedback)

    combined_cwe_ids = sorted(
        set(
            (bandit_result["summary"]["cwe_ids"] or [])
            + (semgrep_result["summary"]["cwe_ids"] or [])
        )
    )

    llm_context = {
        "tool": "security_checks",
        "is_insecure": bandit_result["summary"]["is_insecure"]
        or semgrep_result["summary"]["is_insecure"],
        "cwe_ids": combined_cwe_ids,
        "feedback": merged_feedback,
        "tools": {
            "bandit": {
                "num_issues": bandit_result["summary"]["num_issues"],
                "cwe_ids": bandit_result["summary"]["cwe_ids"],
                "feedback": bandit_feedback,
            },
            "semgrep": {
                "num_issues": semgrep_result["summary"]["num_issues"],
                "cwe_ids": semgrep_result["summary"]["cwe_ids"],
                "feedback": semgrep_feedback,
            },
        },
    }

    artifact = {
        "llm_context": llm_context,
        "verbose": {
            "bandit": {
                "summary": bandit_result["summary"],
                "llm_context": bandit_result["llm_context"],
                "raw_report": bandit_result["raw_report"],
            },
            "semgrep": {
                "summary": semgrep_result["summary"],
                "llm_context": semgrep_feedback,
                "raw_report": semgrep_result["raw_report"],
            },
        },
    }

    return llm_context, artifact
