from __future__ import annotations

from typing import Any

from langchain_core.tools import tool
from pydantic import BaseModel, Field

from codecracker.tools.semgrep import evaluate_code_with_semgrep


class SemgrepToolInput(BaseModel):
    code: str = Field(
        description=(
            "A complete Python code string generated by the model. "
            "Use this tool to check generated Python code for security issues with Semgrep. "
            "Pass the code text itself, not a file path, not Markdown, and not an explanation. "
            "The tool does not execute the code. It returns whether the code is insecure, "
            "the detected CWE IDs, issue counts, and compact actionable feedback."
        )
    )


@tool("run_semgrep", args_schema=SemgrepToolInput)
def run_semgrep_tool(code: str) -> dict[str, Any]:
    """
    Run Semgrep static analysis on generated Python code.

    Use this tool after code generation to check for security issues. The input must be
    the generated Python code as plain text. The tool does not execute the code.

    Returns compact feedback for refinement:
    - is_insecure: whether Semgrep found any security issue
    - num_issues: number of raw Semgrep findings
    - cwe_ids: detected CWE categories
    - feedback: actionable findings with line number, severity, message, and code snippet
    """
    result = evaluate_code_with_semgrep(code)
    summary = result["summary"]

    return {
        "tool": "semgrep",
        "is_insecure": summary["is_insecure"],
        "num_issues": summary["num_issues"],
        "cwe_ids": summary["cwe_ids"],
        "feedback": summary["issues"],
    }


def smoke_test_semgrep_tool() -> None:
    code = """
import subprocess

def run(user_input):
    subprocess.call(user_input, shell=True)
"""

    result = run_semgrep_tool.invoke({"code": code})
    print(result)


if __name__ == "__main__":
    smoke_test_semgrep_tool()
